version: '3.3'
services:

      db:
        container_name: banco
        build:
          context: .
          dockerfile: Dockerfile.mysql
        restart: always
        ports:
          - "3306:3306"
        networks: 
          - compra

      app:
        container_name: compraApp
        image: loja/compra:v1
        hostname: compra
        build:
          context: .
          dockerfile: Dockerfile
        environment: 
          DATABASE_HOST: db
          GET_HOST_FROM: dns
          WAIT_HOSTS: db:3306
        networks: 
        - compra
        volumes: 
        - .:/src/compra
        ports: 
        - 80:3000
        depends_on: 
        - db
        links: 
        - db
        labels: 
            kompose.service.type: LoadBalancer

networks: 
    fornecedor:
        driver: bridge