version: '3.3'
services:

      db:
        container_name: banco
        build:
          context: .
          dockerfile: Dockerfile.mysql
        restart: always
        ports:
          - "3306:3306"
